/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.CarCatalog;
import java.awt.CardLayout;
/**
 *
 * @author saisr
 */
public class MainJFrame extends javax.swing.JFrame {
    private CarCatalog CarCatalog;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.CarCatalog = new CarCatalog ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        ManagerAccessPanel = new javax.swing.JPanel();
        btnUberManager = new javax.swing.JButton();
        SelectActionPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        btnUberManager.setBackground(new java.awt.Color(255, 255, 255));
        btnUberManager.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnUberManager.setForeground(new java.awt.Color(51, 51, 51));
        btnUberManager.setText("MANAGER");
        btnUberManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUberManagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManagerAccessPanelLayout = new javax.swing.GroupLayout(ManagerAccessPanel);
        ManagerAccessPanel.setLayout(ManagerAccessPanelLayout);
        ManagerAccessPanelLayout.setHorizontalGroup(
            ManagerAccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnUberManager, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
        );
        ManagerAccessPanelLayout.setVerticalGroup(
            ManagerAccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnUberManager, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        SplitPane.setLeftComponent(ManagerAccessPanel);

        SelectActionPanel.setBackground(new java.awt.Color(178, 215, 214));
        SelectActionPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setBackground(new java.awt.Color(178, 215, 214));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UBER FLEET MANAGEMENT SYSTEM");
        SelectActionPanel.add(jLabel1, "card2");

        SplitPane.setRightComponent(SelectActionPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUberManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUberManagerActionPerformed
        // TODO add your handling code here:
        ManagerActionPanel panel = new ManagerActionPanel (SelectActionPanel,CarCatalog);
        SelectActionPanel.add("ManagerActionPanel", panel);
        CardLayout layout = (CardLayout) SelectActionPanel.getLayout();
        layout.next(SelectActionPanel);
    }//GEN-LAST:event_btnUberManagerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ManagerAccessPanel;
    private javax.swing.JPanel SelectActionPanel;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton btnUberManager;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
