/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.UberCars;
import model.CarCatalog;
import java.awt.CardLayout;
import java.awt.Component;
import java.security.Timestamp;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author saisr
 */
public class ViewCarDetails extends javax.swing.JPanel {
    private JPanel SelectActionPanel;
    private UberCars ubercars;
    
    private CarCatalog CarCatalog;
   

    ViewCarDetails(JPanel SelectActionPanel, UberCars ubercars) {
        initComponents();
        this.SelectActionPanel = SelectActionPanel;
        this.ubercars = ubercars;
        populateUber();
        
        txtBrand.setEditable(false);
        txtYearofManufacture.setEditable(false);
        txtMaxSeats.setEditable(false);
        txtMinSeats.setEditable(false);
        txtSerialNumber.setEditable(false);
        txtModelNumber.setEditable(false);
        txtCity.setEditable(false);
        btnTrue.setEnabled(false);
        btnFalse.setEnabled(false);
        btnExp.setEnabled(false);
        btnNonExp.setEnabled(false);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        txtSerialNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtModelNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaxSeats = new javax.swing.JTextField();
        txtMinSeats = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtYearofManufacture = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBack5 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtTimestamp = new javax.swing.JTextField();
        btnTrue = new javax.swing.JCheckBox();
        btnFalse = new javax.swing.JCheckBox();
        btnExp = new javax.swing.JCheckBox();
        btnNonExp = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(178, 215, 214));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Year of Manufacture :");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Serial Number :");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Model Number :");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Is the Car Available? :");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Available City :");

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setText("Maintainance Expiration Certificate Status:");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Maximum Seat Capacity :");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Minimum Seat Capacity :");

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("                   VIEW CAR DETAILS");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Brand :");

        btnBack5.setBackground(new java.awt.Color(153, 153, 153));
        btnBack5.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        btnBack5.setText("Back");
        btnBack5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack5ActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnTrue.setBackground(new java.awt.Color(178, 215, 214));
        buttonGroup1.add(btnTrue);
        btnTrue.setText("Yes");
        btnTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrueActionPerformed(evt);
            }
        });

        btnFalse.setBackground(new java.awt.Color(178, 215, 214));
        buttonGroup1.add(btnFalse);
        btnFalse.setText("No");
        btnFalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFalseActionPerformed(evt);
            }
        });

        btnExp.setBackground(new java.awt.Color(178, 215, 214));
        buttonGroup2.add(btnExp);
        btnExp.setText("Expired");

        btnNonExp.setBackground(new java.awt.Color(178, 215, 214));
        buttonGroup2.add(btnNonExp);
        btnNonExp.setText("Non Expired");

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel11.setText("Last Update Occurred On :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack5)
                                .addGap(0, 1406, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4))
                                .addGap(140, 140, 140)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModelNumber)
                                    .addComponent(txtSerialNumber)
                                    .addComponent(txtYearofManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaxSeats)
                                    .addComponent(txtMinSeats)
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7))
                                .addGap(140, 140, 140)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnExp)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnNonExp))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnTrue)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnFalse))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTimestamp, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBrand, txtCity, txtMaxSeats, txtMinSeats, txtModelNumber, txtSerialNumber, txtYearofManufacture});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack5)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(txtYearofManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(txtMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(txtMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnTrue)
                    .addComponent(btnFalse)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnExp)
                    .addComponent(btnNonExp)
                    .addComponent(jLabel10))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTimestamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addGap(96, 96, 96))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBrand, txtCity, txtMaxSeats, txtMinSeats, txtModelNumber, txtSerialNumber, txtYearofManufacture});

    }// </editor-fold>//GEN-END:initComponents

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnUpdate.setEnabled(false);
        btnSave.setEnabled(true);
        txtBrand.setEnabled(true);
        txtYearofManufacture.setEnabled(true);
        txtMaxSeats.setEnabled(true);
        txtMinSeats.setEnabled(true);
        txtSerialNumber.setEnabled(true);
        txtModelNumber.setEnabled(true);
        txtCity.setEnabled(true);
        btnTrue.setEnabled(true);
        btnFalse.setEnabled(true);
        btnExp.setEnabled(true);
        btnNonExp.setEnabled(true);
        txtBrand.setEditable(true);
        txtYearofManufacture.setEditable(true);
        txtMaxSeats.setEditable(true);
        txtMinSeats.setEditable(true);
        txtSerialNumber.setEditable(true);
        txtModelNumber.setEditable(true);
        txtCity.setEditable(true);
   
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String brandname = txtBrand.getText();
        if(brandname == null || brandname.equals(""))
            {
                JOptionPane.showMessageDialog(null,"Enter the Brand name");
                return;
            }
        
        String manuYear = txtYearofManufacture.getText();
        if (manuYear == null || manuYear.equals("")) 
        {
        JOptionPane.showMessageDialog(null,"Enter the Car's Year of Manufacture", " Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }
         try {
            Integer.parseInt(txtYearofManufacture.getText());
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Enter a valid value", " Warning", JOptionPane.WARNING_MESSAGE);
        }   
        
         String maxCapa = txtMaxSeats.getText();
        if (maxCapa == null || maxCapa.equals("")) 
        {
        JOptionPane.showMessageDialog(null,"Enter the Maximum Seat Capacity", " Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }
         try {
            Integer.parseInt(txtMaxSeats.getText());
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Enter a valid value", " Warning", JOptionPane.WARNING_MESSAGE);
        }   
         
          String minCapa = txtMinSeats.getText();
        if (minCapa == null || minCapa.equals("")) 
        {
        JOptionPane.showMessageDialog(null,"Enter the Minimum Seat Capacity", " Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }
         try {
            Integer.parseInt(txtMinSeats.getText());
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null,"You need to put valid value", " Warning", JOptionPane.WARNING_MESSAGE);
        } 
         
         String serNum = txtSerialNumber.getText();
        if (serNum == null || serNum.equals("")) 
        {
        JOptionPane.showMessageDialog(null,"Enter the Serial Number", " Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }
         try {
            Integer.parseInt(txtSerialNumber.getText());
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Enter a valid value", " Warning", JOptionPane.WARNING_MESSAGE);
        } 
         
         String modNum = txtModelNumber.getText();
        if (modNum == null || modNum.equals("")) 
        {
        JOptionPane.showMessageDialog(null,"Enter the Model Number", " Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }
         
         String avaCity = txtCity.getText();
        if (avaCity == null || avaCity.equals("")) 
        {
        JOptionPane.showMessageDialog(null,"Enter the Model Number", " Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        
        
        
        
        
        
        
        ubercars.setBrand(txtBrand.getText());
        ubercars.setYearofManufacture(Integer.parseInt(txtYearofManufacture.getText()));
        ubercars.setMaxSeats(Integer.parseInt(txtMaxSeats.getText()));
        ubercars.setMinSeats(Integer.parseInt(txtMinSeats.getText()));
        ubercars.setSerialNumber(Integer.parseInt(txtSerialNumber.getText()));
        ubercars.setModelNumber(txtModelNumber.getText());
        ubercars.setAvailableCity(txtCity.getText());
        if(btnTrue.isSelected())
        {
            ubercars.setAvailability(true);
        }
        else{ubercars.setAvailability(false);
        }
        
        if(btnExp.isSelected()){
            ubercars.setMaintainanceCertificate(true);
        }
        else{
         ubercars.setMaintainanceCertificate(false);
        }
        
        
        SimpleDateFormat date = new SimpleDateFormat("MM/dd/yyyy, hh:mm:ss");
        Date s = new Date();
        txtTimestamp.setText(date.format(s));
        
        JOptionPane.showMessageDialog(null, "Details updated Successfully");
       
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBack5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack5ActionPerformed
        // TODO add your handling code here:
       

        this.SelectActionPanel.remove(this);
        CardLayout layout = (CardLayout) this.SelectActionPanel.getLayout();
        
        Component[] comps = this.SelectActionPanel.getComponents();
        for (Component comp : comps)
        {
            if (comp instanceof ManageCarDetails){
                ManageCarDetails mngp = (ManageCarDetails) comp;
                mngp.populateTable(CarCatalog,"all");
            }
        }
        Component[] compss = this.SelectActionPanel.getComponents();
        for (Component comp : compss)
        {
            if (comp instanceof FilteredResultsTable){
                FilteredResultsTable mngp = (FilteredResultsTable) comp;
                mngp.populateTable(CarCatalog,"all");
            }
        }
        
        layout.previous(SelectActionPanel);
    }//GEN-LAST:event_btnBack5ActionPerformed

    private void btnTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrueActionPerformed

    private void btnFalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFalseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFalseActionPerformed

    private void populateUber() {
        //To change body of generated methods, choose Tools | Templates.
        txtBrand.setText(ubercars.getBrand());
        txtYearofManufacture.setText(String.valueOf(ubercars.getYearofManufacture()));
        txtMaxSeats.setText(String.valueOf(ubercars.getMaxSeats()));
        txtMinSeats.setText(String.valueOf(ubercars.getMinSeats()));
        txtSerialNumber.setText(String.valueOf(ubercars.getSerialNumber()));
        txtModelNumber.setText(ubercars.getModelNumber());
        txtCity.setText(ubercars.getAvailableCity());
        if(ubercars.isAvailability() == true)
        {
            btnTrue.setEnabled(false);
            btnFalse.setEnabled(false);
            btnTrue.setSelected(true);
        }
        else
        {
            btnTrue.setEnabled(false);
            btnFalse.setEnabled(false);
            btnFalse.setSelected(true);
        }
        if(ubercars.isMaintainanceCertificate()== true)
        {
            btnExp.setEnabled(false);
            btnNonExp.setEnabled(false);
            btnExp.setSelected(true);   
        }
        else
        {
            btnExp.setEnabled(false);
            btnNonExp.setEnabled(false);
            btnNonExp.setSelected(true);
        }
         
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack5;
    private javax.swing.JCheckBox btnExp;
    private javax.swing.JCheckBox btnFalse;
    private javax.swing.JCheckBox btnNonExp;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox btnTrue;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtMaxSeats;
    private javax.swing.JTextField txtMinSeats;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSerialNumber;
    private javax.swing.JTextField txtTimestamp;
    private javax.swing.JTextField txtYearofManufacture;
    // End of variables declaration//GEN-END:variables
}
