/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import model.CarProfileHistory;
import model.CarProfile;
import model.CarProfileHistory;

/**
 *
 * @author saisr
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
    CarProfileHistory history;
    
    
    public ViewJPanel(CarProfileHistory history) {
        initComponents();
        
        this.history = history;
        
        populateTable();
        
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblBrand = new javax.swing.JLabel();
        txtOwnerTelephoneNumber = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        txtOwnerEmailAddress = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        txtOwnerDriverLicense = new javax.swing.JTextField();
        lblYear = new javax.swing.JLabel();
        txtOwnerSocialSecurityNumber = new javax.swing.JTextField();
        lblEngineNumber = new javax.swing.JLabel();
        txtOwnerAddress = new javax.swing.JTextField();
        lblOwnerDriverLicense = new javax.swing.JLabel();
        lblNumberofSeats = new javax.swing.JLabel();
        lblOwnerSocialSecurityNumber = new javax.swing.JLabel();
        lblLicensePlate = new javax.swing.JLabel();
        lblOwnerAddress = new javax.swing.JLabel();
        lblOwnerName = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        txtWarrantyYear = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        lblWarrantyYear = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtEngineNumber = new javax.swing.JTextField();
        txtNumberofSeats = new javax.swing.JTextField();
        txtLicensePlate = new javax.swing.JTextField();
        lblOwnerTelephoneNumber = new javax.swing.JLabel();
        lblOwnerEmailAddress = new javax.swing.JLabel();
        txtOwnerName = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        lblImage = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 153, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("VIEW CAR PROFILE");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Brand", "Model", "Color", "Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lblBrand.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblBrand.setText("Brand:");

        txtOwnerTelephoneNumber.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        lblModel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblModel.setText("Model:");

        txtOwnerEmailAddress.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        lblColor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblColor.setText("Color:");

        txtOwnerDriverLicense.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtOwnerDriverLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwnerDriverLicenseActionPerformed(evt);
            }
        });

        lblYear.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblYear.setText("Year:");

        txtOwnerSocialSecurityNumber.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        lblEngineNumber.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblEngineNumber.setText("Engine Number:");

        txtOwnerAddress.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        lblOwnerDriverLicense.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblOwnerDriverLicense.setText("Owner Driver License:");

        lblNumberofSeats.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblNumberofSeats.setText("Number of Seats:");

        lblOwnerSocialSecurityNumber.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblOwnerSocialSecurityNumber.setText("Owner Social Security Number:");

        lblLicensePlate.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblLicensePlate.setText("License Plate:");

        lblOwnerAddress.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblOwnerAddress.setText("Owner Address:");

        lblOwnerName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblOwnerName.setText("Owner Name:");

        txtBrand.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txtWarrantyYear.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txtModel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        lblWarrantyYear.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblWarrantyYear.setText("Warranty Year:");

        txtColor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txtYear.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txtEngineNumber.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txtNumberofSeats.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txtLicensePlate.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        lblOwnerTelephoneNumber.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblOwnerTelephoneNumber.setText("Owner Telephone Number:");

        lblOwnerEmailAddress.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblOwnerEmailAddress.setText("Owner Email Address:");

        txtOwnerName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Last Maintenance Year", "No.of Accidents", "Odometer Reading", "No.of Previous Owners", "Total Service Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBrand, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblModel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblColor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblYear, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEngineNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNumberofSeats, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLicensePlate, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEngineNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumberofSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOwnerEmailAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOwnerDriverLicense, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOwnerSocialSecurityNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOwnerAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblWarrantyYear, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOwnerName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOwnerTelephoneNumber, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOwnerTelephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOwnerEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOwnerDriverLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOwnerSocialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOwnerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWarrantyYear, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnDelete))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblBrand))
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblModel))
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblColor))
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblYear))
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblEngineNumber))
                            .addComponent(txtEngineNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblNumberofSeats))
                            .addComponent(txtNumberofSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblLicensePlate))
                            .addComponent(txtLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblOwnerName))
                            .addComponent(txtOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblOwnerTelephoneNumber))
                            .addComponent(txtOwnerTelephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblOwnerEmailAddress))
                            .addComponent(txtOwnerEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblOwnerDriverLicense))
                            .addComponent(txtOwnerDriverLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblOwnerSocialSecurityNumber))
                            .addComponent(txtOwnerSocialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblOwnerAddress))
                            .addComponent(txtOwnerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblWarrantyYear))
                            .addComponent(txtWarrantyYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addContainerGap(388, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtOwnerDriverLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwnerDriverLicenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnerDriverLicenseActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
            
           int selectedRowIndex = jTable1.getSelectedRow();
           
           if (selectedRowIndex<0) {
                JOptionPane.showMessageDialog(this, "Please select a row to delete.");
                return;
                
           }
           
           DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
           CarProfile selectedCarProfile = (CarProfile) model.getValueAt(selectedRowIndex , 0);
          
           history.deleteCarProfile(selectedCarProfile);
          
          
           JOptionPane.showMessageDialog(this, "Car Profile deleted.");
          
           populateTable();
         
         
        
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = jTable1.getSelectedRow();
           
           if (selectedRowIndex<0) {
                JOptionPane.showMessageDialog(this, "Please select a row to view.");
                return;
                
           }
           
           DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
           CarProfile selectedCarProfile = (CarProfile) model.getValueAt(selectedRowIndex , 0);
           
           txtBrand.setText(selectedCarProfile.getBrand());
           txtModel.setText(selectedCarProfile.getModel());
           txtColor.setText(selectedCarProfile.getColor());
           txtYear.setText(String.valueOf(selectedCarProfile.getYear()));
           txtEngineNumber.setText(selectedCarProfile.getEngineNumber());
           txtNumberofSeats.setText(String.valueOf(selectedCarProfile.getNumberofSeats()));
           txtLicensePlate.setText(selectedCarProfile.getLicensePlates());
           txtOwnerName.setText(selectedCarProfile.getOwnerName());
           txtOwnerTelephoneNumber.setText(String.valueOf(selectedCarProfile.getOwnerTelephoneNumber()));
           txtOwnerEmailAddress.setText(selectedCarProfile.getOwnerEmailAddress());
           txtOwnerDriverLicense.setText(selectedCarProfile.getOwnerDriverLicense());
           txtOwnerSocialSecurityNumber.setText(String.valueOf(selectedCarProfile.getOwnerSocialSecurityNumber()));
           txtOwnerAddress.setText(selectedCarProfile.getOwnerAddress());
           txtWarrantyYear.setText(String.valueOf(selectedCarProfile.getWarrantyYear()));
           ImageIcon icon = new ImageIcon((selectedCarProfile.getImage()));
           lblImage.setIcon(icon);
           
           populateTable1();
        
        
        
        
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblEngineNumber;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLicensePlate;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblNumberofSeats;
    private javax.swing.JLabel lblOwnerAddress;
    private javax.swing.JLabel lblOwnerDriverLicense;
    private javax.swing.JLabel lblOwnerEmailAddress;
    private javax.swing.JLabel lblOwnerName;
    private javax.swing.JLabel lblOwnerSocialSecurityNumber;
    private javax.swing.JLabel lblOwnerTelephoneNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWarrantyYear;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtEngineNumber;
    private javax.swing.JTextField txtLicensePlate;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtNumberofSeats;
    private javax.swing.JTextField txtOwnerAddress;
    private javax.swing.JTextField txtOwnerDriverLicense;
    private javax.swing.JTextField txtOwnerEmailAddress;
    private javax.swing.JTextField txtOwnerName;
    private javax.swing.JTextField txtOwnerSocialSecurityNumber;
    private javax.swing.JTextField txtOwnerTelephoneNumber;
    private javax.swing.JTextField txtWarrantyYear;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        for (CarProfile cp : history.getHistory()){
            
            Object[] row = new Object[4];
            row[0] = cp;
            row[1] = cp.getModel();
            row[2] = cp.getColor();
            row[3] = cp.getYear();
            
            model.addRow(row);
            
            
        }
        
        
    }
    
    private void populateTable1() {
        
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        model.setRowCount(0);
        
        for (CarProfile cp : history.getHistory()){
            
            Object[] row = new Object[5];
            row[0] = cp.getLastMaintenanceYear();
            row[1] = cp.getNumberofAccidents();
            row[2] = cp.getOdometerReading();
            row[3] = cp.getNumberofPreviousOwners();
            row[4] = cp.getTotalServiceCost();
            
            model.addRow(row);
            
            
        }
        
        
    }
    
    
    
    
}
